# Day 9 - LU2

## Demo: Movie Rating System

**Problem Statement:** 

A movie review website needs to create a database to store their data and perform operations on it. Create a dummy model with 100 users and 1000 movies to explain how it will work.

**Topics Covered:**
- NumPy
    - numpy.ndarray
    - Statistical operations using NumPy
    - Mathematical operations using NumPy
    
**Tasks to be performed:**
1. Generate 1000 movie IDs starting from 1301
2. Create a matrix movies_matrix, to store users rating such that
    - There are 100 users
    - Each user can review as many movies as they want
    - The review should be in between 0 to 10 (both inclusive)
3. We have ten movie experts, let us take their reviews as well. 50 new movies and their reviews have to be added 
4. Create final_movie_rating matrix with four columns i.e., 'Movie ID', 'Average rating', 'Number of ratings', and           'Standard deviation of ratings'
5. Convert the final movie ratings to have range from 0 to 10, such that the minimum rating converts to 0 and maximum to 10, and the other values in between
6. Display the movies rating-wise, highest to lowest

In [ ]:
import numpy as np

In [ ]:
np.set_printoptions(formatter={'float_kind':'{:.3f}'.format})  #Sets the display setting so that all the float values will have 3 values after decimal

#### Task 1: Create a NumPy array of 1000 movie IDs starting from 1301

In [ ]:
movie_id = np.arange(1301,2301)
print(movie_id[:10])
movie_id.size

[1301 1302 1303 1304 1305 1306 1307 1308 1309 1310]


1000

In [ ]:
user_id = []
for i in range(20201,20301):
  user_id.append(i) 
user_id = np.array(user_id)

In [ ]:
user_id.size #checking the number of elements in numpy array

100

In [ ]:
user_id

array([20201, 20202, 20203, 20204, 20205, 20206, 20207, 20208, 20209,
       20210, 20211, 20212, 20213, 20214, 20215, 20216, 20217, 20218,
       20219, 20220, 20221, 20222, 20223, 20224, 20225, 20226, 20227,
       20228, 20229, 20230, 20231, 20232, 20233, 20234, 20235, 20236,
       20237, 20238, 20239, 20240, 20241, 20242, 20243, 20244, 20245,
       20246, 20247, 20248, 20249, 20250, 20251, 20252, 20253, 20254,
       20255, 20256, 20257, 20258, 20259, 20260, 20261, 20262, 20263,
       20264, 20265, 20266, 20267, 20268, 20269, 20270, 20271, 20272,
       20273, 20274, 20275, 20276, 20277, 20278, 20279, 20280, 20281,
       20282, 20283, 20284, 20285, 20286, 20287, 20288, 20289, 20290,
       20291, 20292, 20293, 20294, 20295, 20296, 20297, 20298, 20299,
       20300])

#### Other ways to create a numpy array

In [ ]:
#Creating a Single-Dimensional Array

arr = np.array([2,3,7]) #Calling the Array Function
print(arr)

[2 3 7]


In [ ]:
#Creating a Multi-Dimensional Array

arr = np.array([[10,20,30],[40,50,60]])
print(arr)
print(type(arr))

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>


In [ ]:
#Using np.full()

X = np.full((2,3), 5) #Returns an array with specified shape & filled with specified value
print(X)

[[5 5 5]
 [5 5 5]]


In [ ]:
#Using np.linspace()

arr = np.linspace(0, 20, 5) #Returns a Linearly-Spaced Vector spacing
print(arr)

[0.000 5.000 10.000 15.000 20.000]


#### Task 2: Create a matrix movies_matrix, to store users rating such that
    - There are 100 users
    - Each user can review as many movies as they want
    - The review should be in between 0 to 10 (both inclusive)
    - The movies which are not reviewed by a user should have value -1

In [ ]:
import random
movie_matrix = []
for user in range(100):
  movies_rated_by_me = np.full(1000,-1)
  num_movies_rated = random.randint(0,999)
  #random.seed(num_movies_rated)
  movies_that_i_will_rate = random.sample(range(0,1000),num_movies_rated)
  #user rating for movies they chosed to rate
  for index in movies_that_i_will_rate:
    movies_rated_by_me[index] = random.randint(0,10)
  movie_matrix.append(movies_rated_by_me)



In [ ]:
type(movie_matrix)

list

In [ ]:
len(movie_matrix)

100

In [ ]:
movie_matrix[:3]

[array([-1, -1, -1,  1, -1,  8, -1, -1,  1, -1, 10, -1, -1,  8, -1,  5,  0,
         6, -1, -1,  4, -1, -1, -1,  1, -1, -1,  4,  6,  7,  0,  3,  1, -1,
        -1, -1,  3,  7, -1,  6, -1, -1, -1, -1,  5,  3, 10,  4,  7, -1, -1,
        -1, 10,  7,  8, -1,  0, 10, -1, -1,  4, -1, -1, 10, -1, -1,  0,  2,
         2,  3, -1, -1,  8, -1,  1, -1, -1,  0,  6,  1,  3,  3, -1, -1, -1,
        10, -1, -1, -1,  7, 10, -1,  3,  0, 10, -1, -1,  2, -1, -1,  2,  1,
         7,  1, -1, -1, -1, -1,  2, -1,  7, -1, -1,  4, -1,  5,  5, -1,  7,
         0,  2, -1,  3, -1,  6,  4,  5, -1, 10,  3, 10,  3,  2,  1, -1,  0,
         6, -1,  3, -1, 10,  2,  4, -1, -1, -1,  2, -1, -1, -1, -1, -1,  8,
         8, -1, -1,  2,  2,  7, -1, -1, -1, -1,  6,  5,  7,  4,  0,  3, 10,
        -1, 10, -1,  9, -1,  9,  9,  2,  7, -1,  5,  4,  0,  7,  0,  9,  0,
         0, 10, -1,  7,  3, -1, -1, -1,  3,  9,  5,  5,  7,  9,  4,  2, -1,
        -1,  1, -1,  4,  9, -1,  5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, 

In [ ]:
movie_matrix = np.array(movie_matrix)

Attributes of the numpy ndarray class

In [ ]:
print(movie_matrix)
print('Shape of the array',movie_matrix.shape) #100 users(rows) and 1000 movies(columns)
print('Number of elements in the array',movie_matrix.size)
print('Number of dimensions in the array',movie_matrix.ndim)

[[-1 -1 -1 ...  3 -1  8]
 [ 2  7  5 ...  5  6 10]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [ 6  1  3 ... -1 -1 -1]
 [ 9  7  4 ...  4  4  9]
 [-1  6 -1 ...  5 -1  1]]
Shape of the array (100, 1000)
Number of elements in the array 100000
Number of dimensions in the array 2


#### Task 3: Add the reviews of 10 movie experts and 50 more movies

In [ ]:
#Expert movie reviews

expert_matrix = []
for user in range(10):
  movies_rated_by_me = np.full(1000,-1)
  num_movies_rated = random.randint(0,999)
  #random.seed(num_movies_rated)
  movies_that_i_will_rate = random.sample(range(0,1000),num_movies_rated)
  #user rating for movies they chosed to rate
  for index in movies_that_i_will_rate:
    movies_rated_by_me[index] = random.randint(0,10)
  expert_matrix.append(movies_rated_by_me)
expert_matrix = np.array(expert_matrix)
print(expert_matrix.shape)
expert_matrix

(10, 1000)


array([[ 4, -1,  3, ..., -1, -1, -1],
       [ 9, -1, -1, ...,  9, -1,  9],
       [10, -1,  7, ..., -1, -1, -1],
       ...,
       [-1,  9,  9, ..., -1, -1, -1],
       [ 3, -1, 10, ..., -1, -1, -1],
       [ 3, -1, -1, ..., -1, -1, -1]])

In [ ]:
#adding these expert reviews with original reviews
movie_matrix = np.vstack([movie_matrix,expert_matrix]) # vstack is used to stack arrays vertically
movie_matrix.shape

(110, 1000)

In [ ]:
new_movies_matrix = []
for user in range(110):
  movies_rated_by_me = np.full(50,-1)
  num_movies_rated = random.randint(0,49)
  #random.seed(num_movies_rated)
  movies_that_i_will_rate = random.sample(range(0,50),num_movies_rated)
  #user rating for movies they chosed to rate
  for index in movies_that_i_will_rate:
    movies_rated_by_me[index] = random.randint(0,10)
  new_movies_matrix.append(movies_rated_by_me)
new_movies_matrix = np.array(new_movies_matrix)
print(new_movies_matrix.shape)
new_movies_matrix

(110, 50)


array([[ 8, 10, -1, ...,  4,  1,  6],
       [ 1,  8,  7, ...,  8,  0,  6],
       [-1,  0,  5, ...,  4, -1,  8],
       ...,
       [ 4,  8, -1, ..., -1, -1, -1],
       [ 2,  5,  3, ...,  1,  6, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [ ]:
new_movies_id = np.append(movie_id,np.arange(2301,2351))
new_movies_id.size

1050

In [ ]:
#adding the reviews of new movies with original reviews
movie_matrix = np.hstack([movie_matrix,new_movies_matrix]) # hstack is used to stack arrays horizontally
print(movie_matrix.shape) #100 users + 10 experts(rows) and 1000 + 50 movies(columns)

(110, 1050)


We can see now that we have 110 users and 1050 movies.

#### Indexing and Slicing in NumPy

In [ ]:
#Indexing 
a = np.arange(1,10)
print("Accessed Element:",a[5]) #Accessing a Single Element

Accessed Element: 6


In [ ]:
print('Given Array:',a) 
print('Retrieved Elements:',a[3:])

Given Array: [1 2 3 4 5 6 7 8 9]
Retrieved Elements: [4 5 6 7 8 9]


#### Statistical Function in NumPy

In [ ]:
arr = np.array([[4,9,2],
              [3,1,2]])
print('mean of the array is',arr.mean())
print('Standard deviation of the array is',arr.std()) #std() - Returns the Standard Deviation of the given data. It is the square-root of variance
print('median of the array is',np.median(arr))
print('minimum value in the array is',arr.min())

mean of the array is 3.5
Standard deviation of the array is 2.6299556396765835
median of the array is 2.5
minimum value in the array is 1


In [ ]:
#mean() - Returns the Mean of the given data

arr = np.array([[0,5,7],
              [4,9,1],
              [3,1,7]])
print(np.mean(arr))

print(np.mean(arr,0)) #Mean along axis - 0

print(np.mean(arr,1)) #Mean along axis - 1

4.111111111111111
[2.333 5.000 5.000]
[4.000 4.667 3.667]


#### Task 4: Create final_movie_rating matrix with four columns i.e., 
- 'Movie ID'
- 'Average rating'
- 'Number of ratings'
- 'Standard deviation of ratings'

In [ ]:
final_movie_rating = []
for i in range(1050):
  #each movie's rating
  m = movie_matrix[:,i] # taking all rows and the ith column
  m = m[m>=0]
  #total_rate = m.sum()
  total_num_rating = m.size
  rating = m.mean()
  standard_deviation = m.std()
  final_movie_rating.append([new_movies_id[i],rating,total_num_rating,standard_deviation])

In [ ]:
final_movie_rating = np.array(final_movie_rating)
final_movie_rating

array([[1301.000, 5.548, 62.000, 2.987],
       [1302.000, 4.773, 66.000, 2.880],
       [1303.000, 5.509, 57.000, 3.250],
       ...,
       [2348.000, 4.947, 57.000, 3.241],
       [2349.000, 4.382, 55.000, 3.366],
       [2350.000, 5.259, 54.000, 2.723]])

#### Mathematical Operation using NumPy

In [ ]:
#add() - Used to add arguments element-wise

a = np.array([[2,0],
              [4,9]])
b = np.array([[2,0],
              [4,9]])
print(np.add(a,b))
print("Another way to perform element-wise operation\n",a+b)
print("1 added to Matrix 'a' element-wise\n ",a+1)

[[ 4  0]
 [ 8 18]]
Another way to perform element-wise operation
 [[ 4  0]
 [ 8 18]]
1 added to Matrix 'a' element-wise
  [[ 3  1]
 [ 5 10]]


In [ ]:
#subtract() - Used to subtract arguments element-wise

a = np.array([[10,20,30]])
b = np.array([[10,10,10]])
np.subtract(a,b)


array([[ 0, 10, 20]])

In [ ]:
#multiply() - Used to add multiply arguments element-wise

a = np.array([[0,5,7],
              [4,9,1],
              [3,1,7]])
b = np.array([[10,10,10]])
np.multiply(a,b)

array([[ 0, 50, 70],
       [40, 90, 10],
       [30, 10, 70]])

In [ ]:
#divide() - Used to divide arguments element-wise

a = np.array([[20,24,32],
              [4,8,18],
              [2,54,78]])
b = np.array([[2]])
np.divide(a,b)

array([[10.000, 12.000, 16.000],
       [2.000, 4.000, 9.000],
       [1.000, 27.000, 39.000]])

In [ ]:
#ceil() -Returns the ceiling of an input value

arr = [7.5, 21.5, 42.8, 43.7, 14.2, 32.6, 51.9, 2.5, 1.9] 
print("Input array : \n",arr) 

print("Ceiling Values:\n",np.ceil(arr)) 

Input array : 
 [7.5, 21.5, 42.8, 43.7, 14.2, 32.6, 51.9, 2.5, 1.9]
Ceiling Values:
 [8.000 22.000 43.000 44.000 15.000 33.000 52.000 3.000 2.000]


#### Task 5: Convert the final movie ratings to have range from 0 to 10, such that the minimum rating converts to 0 and maximum to 10, and the other values in between

In [ ]:
#Converting the average of movie ratings to have the range 0 to 10
x = final_movie_rating[:,1]
old_range = x.max()-x.min()
new_range = (10 - 0)
final_movie_rating[:,1] = ((x - x.min())*(new_range/old_range) + 0)

In [ ]:
final_movie_rating

array([[1301.000, 6.954, 62.000, 2.987],
       [1302.000, 3.798, 66.000, 2.880],
       [1303.000, 6.793, 57.000, 3.250],
       ...,
       [2348.000, 4.509, 57.000, 3.241],
       [2349.000, 2.208, 55.000, 3.366],
       [2350.000, 5.778, 54.000, 2.723]])

In [ ]:
final_movie_rating.shape

(1050, 4)

#### Task 6: Display the movies rating-wise, highest to lowest

In [ ]:
sorted_films = final_movie_rating[final_movie_rating[:,1].argsort()[::-1]]

In [ ]:
print(sorted_films)

[[2118.000 10.000 64.000 2.854]
 [1376.000 9.213 58.000 2.958]
 [1968.000 9.073 58.000 2.906]
 ...
 [1566.000 0.277 54.000 2.843]
 [1613.000 0.129 62.000 2.876]
 [2276.000 0.000 56.000 2.658]]


**savetxt()** method is used to write files from a NumPy array.

In [ ]:
np.savetxt('ranked_movie_data.csv',sorted_films, delimiter=',')

**genfromtxt()** method is used to read files in a NumPy array.

In [ ]:
data = np.genfromtxt('ranked_movie_data.csv',delimiter = ',')

In [ ]:
data

array([[2118.000, 10.000, 64.000, 2.854],
       [1376.000, 9.213, 58.000, 2.958],
       [1968.000, 9.073, 58.000, 2.906],
       ...,
       [1566.000, 0.277, 54.000, 2.843],
       [1613.000, 0.129, 62.000, 2.876],
       [2276.000, 0.000, 56.000, 2.658]])

**If you want to learn more about NumPy [Click Here](https://numpy.org/devdocs/user/quickstart.html).**